CREATE OR REPLACE TRIGGER MOVIE_INSERT
AFTER INSERT ON MOVIES
BEGIN
	DBMS_OUTPUT.PUT_LINE('MOVIE INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER CUSTOMER_INSERT
AFTER INSERT ON CUSTOMER
BEGIN
	DBMS_OUTPUT.PUT_LINE('CUSTOMER INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER MANAGER_INSERT
AFTER INSERT ON MANAGER
BEGIN
	DBMS_OUTPUT.PUT_LINE('MANAGER INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER HALL_INSERT
AFTER INSERT ON HALL
BEGIN
	DBMS_OUTPUT.PUT_LINE('HALL INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER SHOW_INSERT
AFTER INSERT ON SHOW
BEGIN
	DBMS_OUTPUT.PUT_LINE('SHOW INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER SCHEDULE_INSERT
AFTER INSERT ON SCHEDULE
BEGIN
	DBMS_OUTPUT.PUT_LINE('SCHEDULE INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER SEAT_INSERT
AFTER INSERT ON SEATTYPE
BEGIN
	DBMS_OUTPUT.PUT_LINE('SEATTYPE INSERTED!');
END;
/

CREATE OR REPLACE TRIGGER TICKET_INSERT
AFTER INSERT ON TICKET
BEGIN
	DBMS_OUTPUT.PUT_LINE('TICKET PURCHASED!');
END;
/

CREATE OR REPLACE TRIGGER PAYMENT_INSERT
AFTER INSERT ON PAYMENT
BEGIN
	DBMS_OUTPUT.PUT_LINE('PAYMENT SUCCESSFUL!');
END;
/