CREATE OR REPLACE VIEW VIEW_MOHAKHALI AS
SELECT S_ID, H_ID,SHOWDATE FROM SCHEDULE WHERE M_ID 
IN (SELECT MOVIEID FROM MOVIES WHERE TITLE = 'MOONFALL');

CREATE OR REPLACE VIEW VIEW_PANTHAPATH AS
SELECT S_ID, H_ID,SHOWDATE FROM SCHEDULE@SITE_PANTHAPATH WHERE M_ID 
IN (SELECT MOVIEID FROM MOVIES@SITE_PANTHAPATH WHERE TITLE = 'MOONFALL');

SELECT * FROM VIEW_MOHAKHALI;
SELECT * FROM VIEW_PANTHAPATH;