DROP VIEW VIEW_PANTHAPATH;
DROP VIEW VIEW_MOHAKHALI;

CREATE OR REPLACE VIEW VIEW_PANTHAPATH AS
SELECT S_ID, H_ID,SHOWDATE FROM SCHEDULE WHERE M_ID 
IN (SELECT MOVIEID FROM MOVIES WHERE TITLE = 'MOONFALL');

CREATE OR REPLACE VIEW VIEW_MOHAKHALI AS
SELECT S_ID, H_ID,SHOWDATE FROM SCHEDULE@SITE_MOHAKHALI WHERE M_ID 
IN (SELECT MOVIEID FROM MOVIES@SITE_MOHAKHALI WHERE TITLE = 'MOONFALL');

SELECT * FROM VIEW_PANTHAPATH;
SELECT * FROM VIEW_MOHAKHALI;