DROP PACKAGE CINEPLEX;
DROP PACKAGE CINEPLEX_ADMIN;

CREATE OR REPLACE PACKAGE CINEPLEX AS
	PROCEDURE DISPLAY_HALL(N IN NUMBER);
	
	PROCEDURE DISPLAY_SHOW(N IN NUMBER);
	
	PROCEDURE DISPLAY_SCHEDULE(N IN NUMBER);
	
	PROCEDURE DISPLAY_SEAT(N IN NUMBER);
	
	PROCEDURE DISPLAY_MOVIES(N IN NUMBER);
	
	PROCEDURE MOVIE_SPECIFIC_INFORMATION(N IN NUMBER, M IN SCHEDULE.M_ID%TYPE);
	
	PROCEDURE BUY_TICKETS(N IN VENUE.VENUEID%TYPE, S IN SHOW.SHOWID%TYPE, ST IN TICKET.ST_ID%TYPE, M IN MOVIES.MOVIEID%TYPE, C IN PAYMENT.C_ID%TYPE);
	
	PROCEDURE USER_HISTORY(N IN VENUE.VENUEID%TYPE, C IN PAYMENT.C_ID%TYPE);
	
END CINEPLEX;
/

CREATE OR REPLACE PACKAGE CINEPLEX_ADMIN AS
	PROCEDURE DISPLAY_MANAGER(N IN NUMBER);
	PROCEDURE REVENUE_INFORMATION(N IN NUMBER);
END CINEPLEX_ADMIN;
/