CREATE OR REPLACE FUNCTION FIND_AMOUNT(S IN TICKET.ST_ID%TYPE, B IN HALL.HALLID%TYPE)
RETURN PAYMENT.AMOUNT%TYPE
IS 
	A PAYMENT.AMOUNT%TYPE;
	
BEGIN
	
	IF (B = 1 OR B = 2 OR B = 3) THEN
		IF S = 1 THEN
			A := 500;
		ELSIF S = 2 THEN
			A := 400;
		ELSIF S =3  THEN
			A := 350;	
		END IF;	
		
	ELSIF (B = 4) THEN
		IF S = 1 THEN
			A := 700;
		ELSIF S = 2 THEN
			A := 600;
		ELSIF S = 3  THEN
			A := 500;	
		END IF;
	ELSE 
		A := 0;		
	END IF;
	RETURN A;
END FIND_AMOUNT;
/