SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT 1 - PANTHAPATH
PROMPT 2 - MOHAKHALI
ACCEPT v NUMBER PROMPT 'SELECT A VENUE : ';
PROMPT
PROMPT _______________________________OPTIONS__________________
PROMPT 1.Halls | 2.Show Times | 3.Seat Types | 4.Movie Schedule  
PROMPT 5. Movies Playing
PROMPT 6. Movie Specific Information
PROMPT 7. Buy Tickets
PROMPT 8. User History
ACCEPT u NUMBER PROMPT 'SELECT AN OPTION : ';

DECLARE
	v number;
	uOpt number;
	sid SHOW.SHOWID%TYPE := 1;
	stid TICKET.ST_ID%TYPE := 1;
	mid MOVIES.MOVIEID%TYPE := 2;
	uid PAYMENT.C_ID%TYPE := 1;

BEGIN
	v:= &v;
	uOpt:= &u;
	DBMS_OUTPUT.PUT_LINE(chr(10));
	
	IF (v = 1 OR v = 2 ) then
		CASE uOpt
			WHEN 1 THEN CINEPLEX.DISPLAY_HALL(v);
			WHEN 2 THEN CINEPLEX.DISPLAY_SHOW(v);
			WHEN 3 THEN CINEPLEX.DISPLAY_SEAT(v);
			WHEN 4 THEN CINEPLEX.DISPLAY_SCHEDULE(v);
			WHEN 5 THEN CINEPLEX.DISPLAY_MOVIES(v);
			WHEN 6 THEN CINEPLEX.MOVIE_SPECIFIC_INFORMATION(v,1);	
			WHEN 7 THEN 
				DBMS_OUTPUT.PUT_LINE('SHOW ID : ' || sid || '  SEATTYPE ID : ' || stid || '  MOVIE ID : ' || mid || '  USER ID : ' || uid);
				CINEPLEX.BUY_TICKETS(v,sid,stid,mid,uid);
			WHEN 8 THEN CINEPLEX.USER_HISTORY(v,1);
			ELSE DBMS_OUTPUT.PUT_LINE('INVALID OPTION');
		END CASE;
		
	ELSE
		DBMS_OUTPUT.PUT_LINE('INVALID INPUT FOR VENUE');
	END IF;

EXCEPTION 
   	WHEN no_data_found THEN 
      	DBMS_OUTPUT.PUT_LINE('WRONG QUERY!'); 
   	WHEN others THEN 
      	DBMS_OUTPUT.PUT_LINE('ERROR DETECTED!');
END;
/