SET SERVEROUTPUT ON;
SET VERIFY OFF;

PROMPT 1 - PANTHAPATH
PROMPT 2 - MOHAKHALI
PROMPT 3 - All VENUES
ACCEPT v NUMBER PROMPT 'SELECT A VENUE : ';
PROMPT
PROMPT ________OPTIONS_______
PROMPT 1. Manger Info
PROMPT 2. Revenue Info
ACCEPT a NUMBER PROMPT 'SELECT AN OPTION : ';

DECLARE
	vOpt number;
	aOpt number;

BEGIN
	vOpt:= &v;
	aOpt:= &a;
	DBMS_OUTPUT.PUT_LINE(chr(10));
	
	IF (vOpt = 1 OR vOpt = 2 OR vOpt = 3) then
		CASE aOpt
			WHEN 1 THEN CINEPLEX_ADMIN.DISPLAY_MANAGER(vOpt);
			WHEN 2 THEN CINEPLEX_ADMIN.REVENUE_INFORMATION(vOpt);	
			ELSE DBMS_OUTPUT.PUT_LINE('INVALID OPTION');
		END CASE;
		
	ELSE
		DBMS_OUTPUT.PUT_LINE('INVALID INPUT FOR VENUE.');
	END IF;

EXCEPTION 
   	WHEN no_data_found THEN 
      	DBMS_OUTPUT.PUT_LINE('WRONG QUERY!'); 
   	WHEN others THEN 
      	DBMS_OUTPUT.PUT_LINE('ERROR DETECTED!');
END;
/